name: Continuos Integration

on:
  push: 
    branches: ['*']

jobs: 
  meu-primeiro-continuos-integration:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ["18.x", "20.x"]

    steps:
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        
      - name: Configurar Node.js ${{ matrix.node-version }}  
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
      
      - name: Rodar instalação e build
        run: |
          npm ci
          npm run build
      
      - name: Rodar aplicação
        run: npm run dev

      - name: Rodar testes
        run: npm run test